# Generated by Django 5.2.8 on 2026-07-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_label', models.CharField(default='FEATURED', help_text="Small pill shown above the heading, e.g. 'FEATURED'.", max_length=30)),
                ('heading', models.CharField(help_text="e.g. 'The New Hyundai Creta'", max_length=100)),
                ('subtitle', models.CharField(help_text="e.g. 'Bold. Powerful. Loaded with next-gen smart features.'", max_length=200)),
                ('image', models.ImageField(help_text='Recommended: compress first (TinyPNG/Squoosh) — this image loads full-width.', upload_to='featured_models/')),
                ('cta_label', models.CharField(blank=True, default='View Details', max_length=50)),
                ('cta_link', models.CharField(blank=True, default='#models', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Only one active row is shown on the site at a time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Featured Model Banner',
                'verbose_name_plural': 'Featured Model Banner',
                'ordering': ['-updated_at'],
            },
        ),
    ]
