# Generated by Django 5.2.8 on 2026-07-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Hyundai Creta'", max_length=80)),
                ('category_label', models.CharField(help_text="e.g. 'Premium SUV', 'Compact SUV'", max_length=40)),
                ('image', models.ImageField(upload_to='car_models/')),
                ('price', models.DecimalField(decimal_places=2, help_text='In Lakhs, e.g. 11.00', max_digits=10)),
                ('mileage_label', models.CharField(help_text="e.g. '17.7 kmpl' or '631 km range'", max_length=30)),
                ('transmission_label', models.CharField(default='Auto/Manual', max_length=30)),
                ('fuel_type_label', models.CharField(help_text="e.g. 'Petrol/Diesel', 'Electric'", max_length=30)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first (left side).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Car Model',
                'verbose_name_plural': 'Car Models',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CarModelsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='Featured Hyundai Models', max_length=60)),
                ('heading_line1', models.CharField(default='Explore the latest', max_length=100)),
                ('heading_highlight', models.CharField(default='Hyundai lineup', help_text='Shown with the navy-to-cyan gradient style.', max_length=50)),
                ('subtitle', models.CharField(default='From city hatchbacks to premium SUVs and electric vehicles — find your perfect Hyundai.', max_length=250)),
                ('footnote', models.CharField(blank=True, default='*Ex-showroom prices. On-road pricing varies by city & variant.', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Car Models Section — Header',
                'verbose_name_plural': 'Car Models Section — Header',
            },
        ),
        migrations.AlterField(
            model_name='featuredmodel',
            name='badge_label',
            field=models.CharField(default='FEATURED', max_length=30),
        ),
        migrations.AlterField(
            model_name='featuredmodel',
            name='heading',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='featuredmodel',
            name='image',
            field=models.ImageField(upload_to='featured_models/'),
        ),
        migrations.AlterField(
            model_name='featuredmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='featuredmodel',
            name='subtitle',
            field=models.CharField(max_length=200),
        ),
    ]
