# Generated by Django 5.2.8 on 2026-07-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carmodel_carmodelssection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodelssection',
            name='heading_highlight',
            field=models.CharField(default='latest Hyundai lineup', help_text='Shown with the navy-to-cyan gradient style.', max_length=50),
        ),
        migrations.AlterField(
            model_name='carmodelssection',
            name='heading_line1',
            field=models.CharField(default='Explore the', max_length=100),
        ),
    ]
