# Generated by Django 5.2.8 on 2026-07-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_carmodelssection_heading_highlight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredmodel',
            name='image_alt',
            field=models.CharField(blank=True, default='Hyundai Showroom', help_text="SEO alt text describing the banner image (e.g. 'Hyundai Showroom in Theni').", max_length=150),
        ),
    ]
