# Generated by Django 5.2.8 on 2026-07-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_featuredmodel_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='image_alt',
            field=models.CharField(blank=True, help_text="SEO alt text for the car image, e.g. 'Hyundai Creta SUV'.", max_length=120),
        ),
    ]
