# Generated by Django 5.2.8 on 2026-08-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carmodel_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='detail_image',
            field=models.ImageField(blank=True, help_text="Optional wide lifestyle/scenic photo shown as the background in the car's detail popup (e.g. car parked against a scenic backdrop). Falls back to the regular gradient card image if left blank.", null=True, upload_to='car_models_detail/'),
        ),
    ]
