# Generated by Django 5.2.8 on 2026-08-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_carmodel_detail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='detail_image_alt',
            field=models.CharField(blank=True, help_text="SEO alt text for the detail popup's lifestyle photo, e.g. 'Hyundai Alcazar parked outside a grand estate'. Falls back to the regular image alt text if left blank.", max_length=150),
        ),
    ]
