# Generated by Django 5.0.6 on 2026-07-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('interested_model', models.CharField(max_length=100)),
                ('preferred_contact_time', models.CharField(choices=[('Morning (9 AM – 12 PM)', 'Morning (9 AM – 12 PM)'), ('Afternoon (12 PM – 4 PM)', 'Afternoon (12 PM – 4 PM)'), ('Evening (4 PM – 8 PM)', 'Evening (4 PM – 8 PM)')], max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('test_drive_booked', 'Test Drive Booked'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
