# Generated by Django 5.2.8 on 2026-07-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='message',
            field=models.TextField(blank=True, help_text="Optional message — only used by the Contact 'Send an Enquiry' form."),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('hero', 'Hero — Get Free Quote'), ('contact', 'Contact — Send an Enquiry')], default='hero', help_text='Which form on the site this lead came from.', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='preferred_contact_time',
            field=models.CharField(blank=True, choices=[('Morning (9 AM – 12 PM)', 'Morning (9 AM – 12 PM)'), ('Afternoon (12 PM – 4 PM)', 'Afternoon (12 PM – 4 PM)'), ('Evening (4 PM – 8 PM)', 'Evening (4 PM – 8 PM)')], help_text='Only used by the Hero quote form. Left blank for Contact-form leads.', max_length=50),
        ),
    ]
