# Generated by Django 5.2.8 on 2026-08-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_message_lead_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Optional — collected via the Book Test Drive popup.', max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='preferred_contact_time',
            field=models.CharField(blank=True, choices=[('Morning (9 AM – 12 PM)', 'Morning (9 AM – 12 PM)'), ('Afternoon (12 PM – 4 PM)', 'Afternoon (12 PM – 4 PM)'), ('Evening (4 PM – 8 PM)', 'Evening (4 PM – 8 PM)')], help_text='Only used by the Hero quote form. Left blank for other sources.', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('hero', 'Hero — Get Free Quote'), ('contact', 'Contact — Send an Enquiry'), ('test_drive', 'Book Test Drive Popup')], default='hero', help_text='Which form on the site this lead came from.', max_length=20),
        ),
    ]
