# Generated by Django 5.2.8 on 2026-08-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_email_alter_lead_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='offer_interested',
            field=models.CharField(blank=True, default='', help_text="Name of the offer the customer clicked 'Claim Offer' on, if any (e.g. 'Cash Discount').", max_length=120),
        ),
    ]
