# Generated by Django 5.2.8 on 2026-07-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Authorized Hyundai Dealer · Best Price Guaranteed', max_length=150)),
                ('heading_line1', models.CharField(default='Drive home your dream', max_length=100)),
                ('heading_highlight', models.CharField(default='Hyundai', help_text='This word is shown with the blue-to-cyan gradient style.', max_length=50)),
                ('heading_line2', models.CharField(default='today', max_length=50)),
                ('paragraph', models.TextField(default='Explore the latest Hyundai models with exclusive offers, easy finance options, exchange benefits and instant test drive booking at Hyundai Susee Showroom.')),
                ('cta_book_label', models.CharField(default='Book Test Drive', max_length=50)),
                ('cta_offer_label', models.CharField(default='Get Best Offer', max_length=50)),
                ('cta_whatsapp_label', models.CharField(default='WhatsApp Now', max_length=50)),
                ('feature_1_label', models.CharField(default='Authorized', max_length=50)),
                ('feature_2_label', models.CharField(default='Easy Finance', max_length=50)),
                ('feature_3_label', models.CharField(default='Exchange Bonus', max_length=50)),
                ('form_title', models.CharField(default='Get Instant Best Price', max_length=100)),
                ('form_subtitle', models.CharField(default='Fill in the details — our advisor will call within 15 minutes.', max_length=200)),
                ('form_badge_text', models.CharField(default='LIMITED TIME OFFER', max_length=50)),
                ('form_footnote', models.CharField(default='Your information is 100% safe & secure', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section Content',
                'verbose_name_plural': 'Hero Section Content',
            },
        ),
    ]
