# Generated by Django 5.2.8 on 2026-07-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('check-circle', 'Check Circle (verified/authorized)'), ('shield-check', 'Shield Check (genuine/protection)'), ('wallet', 'Wallet (finance/money)'), ('repeat', 'Repeat (exchange)'), ('percent', 'Percent (discount)'), ('truck', 'Truck (delivery)'), ('users', 'Users (people/advisors)'), ('calendar', 'Calendar (booking)'), ('phone', 'Phone (contact)'), ('message-circle', 'Message Circle (chat/support)')], default='check-circle', max_length=30)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Why Choose Card',
                'verbose_name_plural': 'Why Choose Cards',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='Why Choose Hyundai Susee', max_length=60)),
                ('heading_line1', models.CharField(default="India's most trusted Hyundai", max_length=100)),
                ('heading_highlight', models.CharField(default='dealer', help_text='This word is shown with the navy-to-cyan gradient style.', max_length=50)),
                ('subtitle', models.CharField(default='Everything you need for a seamless car buying experience — from authorized service to unbeatable offers.', max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Why Choose Section — Header',
                'verbose_name_plural': 'Why Choose Section — Header',
            },
        ),
    ]
