# Generated by Django 5.2.8 on 2026-07-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0002_whychoosecard_whychoosesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('wallet', 'Wallet (cash discount)'), ('repeat', 'Repeat (exchange bonus)'), ('percent', 'Percent (EMI/discount)'), ('users', 'Users (corporate offers)'), ('sparkles', 'Sparkles (festival offers)'), ('gift', 'Gift (free accessories)'), ('shield-check', 'Shield Check'), ('check-circle', 'Check Circle')], default='wallet', max_length=30)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=200)),
                ('cta_label', models.CharField(default='Claim Offer', max_length=40)),
                ('cta_link', models.CharField(default='#contact', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Offer Card',
                'verbose_name_plural': 'Offer Cards',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OffersSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='Exclusive Offers', max_length=60)),
                ('heading_line1', models.CharField(default='Unbeatable Hyundai offers', max_length=100)),
                ('heading_highlight', models.CharField(default='this month', help_text='Shown with the navy-to-cyan gradient style.', max_length=50)),
                ('subtitle', models.CharField(default='Save more with our current benefits, festival specials and corporate deals — limited stock available.', max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Offers Section — Header',
                'verbose_name_plural': 'Offers Section — Header',
            },
        ),
    ]
