# Generated by Django 5.2.8 on 2026-07-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0003_offercard_offerssection'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceFeatureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('percent', 'Percent (Low EMI)'), ('check-circle', 'Check Circle (Instant Approval)'), ('wallet', 'Wallet (100% Finance)'), ('shield-check', 'Shield Check (Insurance)')], default='percent', max_length=30)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Finance Feature Card',
                'verbose_name_plural': 'Finance Feature Cards',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FinancePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'HDFC Bank'", max_length=60)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Finance Partner',
                'verbose_name_plural': 'Finance Partners',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='Finance & Insurance', max_length=60)),
                ('heading_line1', models.CharField(default='Easy finance, simple', max_length=100)),
                ('heading_highlight', models.CharField(default='ownership', help_text='Shown with the navy-to-cyan gradient style.', max_length=50)),
                ('subtitle', models.CharField(default="Partnered with India's leading banks and NBFCs to make owning your Hyundai easier than ever.", max_length=250)),
                ('partners_heading', models.CharField(default='Our Finance Partners', max_length=80)),
                ('partners_subtitle', models.CharField(default="Get instant loan quotations from India's top banks & NBFCs.", max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Finance Section — Header',
                'verbose_name_plural': 'Finance Section — Header',
            },
        ),
    ]
