# Generated by Django 5.2.8 on 2026-07-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0004_financefeaturecard_financepartner_financesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDriveCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Free & Doorstep', max_length=60)),
                ('heading', models.CharField(default='Book Your Free Test Drive Today', max_length=120)),
                ('paragraph', models.CharField(default="Experience the Hyundai you love — right at your doorstep. Pick your model, choose your time, and we'll bring the car to you.", max_length=250)),
                ('cta_book_label', models.CharField(default='Book Test Drive', max_length=50)),
                ('cta_whatsapp_label', models.CharField(default='WhatsApp Now', max_length=50)),
                ('whatsapp_number', models.CharField(default='910000000000', help_text='Digits only, with country code, no + or spaces — e.g. 919876543210', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Test Drive CTA Banner',
                'verbose_name_plural': 'Test Drive CTA Banner',
            },
        ),
    ]
