# Generated by Django 5.2.8 on 2026-07-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0005_testdrivecta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=80)),
                ('purchased_model', models.CharField(help_text="e.g. 'Hyundai Creta'", max_length=80)),
                ('review_text', models.TextField(max_length=400)),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='1 to 5 stars.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestimonialsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='Customer Stories', max_length=60)),
                ('heading_line1', models.CharField(default='Loved by thousands of', max_length=100)),
                ('heading_highlight', models.CharField(default='Hyundai owners', help_text='Shown with the navy-to-cyan gradient style.', max_length=50)),
                ('subtitle', models.CharField(default='Real experiences from happy customers who trusted Hyundai Susee for their car buying journey.', max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonials Section — Header',
                'verbose_name_plural': 'Testimonials Section — Header',
            },
        ),
    ]
