# Generated by Django 5.2.8 on 2026-07-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0006_testimonial_testimonialssection'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(help_text="e.g. 'Showroom Exterior'", max_length=80)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GallerySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='Showroom Gallery', max_length=60)),
                ('heading_line1', models.CharField(default='Step inside Hyundai', max_length=100)),
                ('heading_highlight', models.CharField(default='Susee', help_text='Shown with the navy-to-cyan gradient style.', max_length=50)),
                ('subtitle', models.CharField(default='A glimpse of our showroom, delivery moments and the premium Hyundai experience.', max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Section — Header',
                'verbose_name_plural': 'Gallery Section — Header',
            },
        ),
    ]
