# Generated by Django 5.2.8 on 2026-07-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0007_galleryimage_gallerysection'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_to', models.PositiveIntegerField(help_text='The number to count up to, e.g. 1, 25, 5, 100.')),
                ('suffix', models.CharField(default='+', help_text="e.g. '+', 'M+', '★'", max_length=10)),
                ('label', models.CharField(help_text="e.g. 'Happy Hyundai Customers'", max_length=80)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Trusted Stat',
                'verbose_name_plural': 'Trusted Stats',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrustedStatsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Why Hyundai', max_length=60)),
                ('heading', models.CharField(default='Trusted by millions across India', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trusted Stats Banner — Header',
                'verbose_name_plural': 'Trusted Stats Banner — Header',
            },
        ),
    ]
