# Generated by Django 5.2.8 on 2026-07-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0008_trustedstat_trustedstatssection'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField(max_length=600)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ Item',
                'verbose_name_plural': 'FAQ Items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FAQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='FAQ', max_length=60)),
                ('heading_line1', models.CharField(default='Frequently asked', max_length=100)),
                ('heading_highlight', models.CharField(default='questions', help_text='Shown with the navy-to-cyan gradient style.', max_length=50)),
                ('subtitle', models.CharField(default='Everything you need to know before you buy your next Hyundai.', max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ Section — Header',
                'verbose_name_plural': 'FAQ Section — Header',
            },
        ),
    ]
