# Generated by Django 5.2.8 on 2026-07-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0009_faqitem_faqsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='Visit Us', max_length=60)),
                ('heading_line1', models.CharField(default='Get in touch with', max_length=100)),
                ('heading_highlight', models.CharField(default='Hyundai Susee', help_text='Shown with the navy-to-cyan gradient style.', max_length=50)),
                ('subtitle', models.CharField(default="Drop by our showroom, call us, or send an enquiry — we're here to help you drive home your dream Hyundai.", max_length=250)),
                ('address_line1', models.CharField(default='Susee Auto Complex, Main Road', max_length=150)),
                ('address_line2', models.CharField(default='Madurai, Tamil Nadu 625001', max_length=150)),
                ('phone_1', models.CharField(default='+91 98765 43210', max_length=20)),
                ('phone_2', models.CharField(blank=True, default='+91 98765 43211', max_length=20)),
                ('email', models.EmailField(default='sales@hyundaisusee.com', max_length=254)),
                ('working_hours_weekday', models.CharField(default='Mon – Sat: 9:00 AM – 8:00 PM', max_length=80)),
                ('working_hours_weekend', models.CharField(default='Sun: 10:00 AM – 5:00 PM', max_length=80)),
                ('map_latitude', models.FloatField(default=9.9252, help_text='Used for the embedded map.')),
                ('map_longitude', models.FloatField(default=78.1198, help_text='Used for the embedded map.')),
                ('map_place_label', models.CharField(default='Madurai', help_text='Label shown on the map card (e.g. city or showroom name).', max_length=100)),
                ('form_heading', models.CharField(default='Send an Enquiry', max_length=100)),
                ('form_subtitle', models.CharField(default='Get personalized quotes, offers and finance options.', max_length=200)),
                ('form_submit_label', models.CharField(default='Submit Enquiry', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Section',
                'verbose_name_plural': 'Contact Section',
            },
        ),
    ]
