# Generated by Django 5.2.8 on 2026-07-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0010_contactsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Authorized Hyundai dealer offering the complete Hyundai range with best price, easy finance and premium service.', max_length=250)),
                ('copyright_text', models.CharField(default='© 2026 Hyundai Susee Showroom. All rights reserved.', max_length=150)),
                ('privacy_policy_url', models.CharField(default='#', max_length=200)),
                ('terms_url', models.CharField(default='#', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer Section',
                'verbose_name_plural': 'Footer Section',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('twitter', 'Twitter / X'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('url', models.URLField(max_length=250)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['order', 'id'],
            },
        ),
    ]
