# Generated by Django 5.2.8 on 2026-07-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0011_footersection_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsection',
            name='map_description',
            field=models.CharField(blank=True, default='Serving customers from Theni, Periyakulam, Bodinayakanur, Cumbum, Chinnamanur, Andipatti, and nearby areas.', help_text='Short text shown below the map heading.', max_length=250),
        ),
        migrations.AddField(
            model_name='contactsection',
            name='map_title',
            field=models.CharField(default='Find Our Hyundai Showroom', help_text='Heading shown above the embedded map.', max_length=100),
        ),
    ]
