# Generated by Django 5.2.8 on 2026-07-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0012_contactsection_map_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='image_alt',
            field=models.CharField(blank=True, help_text="SEO alt text for this image, e.g. 'Hyundai Susee Showroom Exterior'. Falls back to the caption if left blank.", max_length=150),
        ),
    ]
