# Generated by Django 5.2.8 on 2026-08-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0013_galleryimage_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersection',
            name='privacy_policy_file',
            field=models.FileField(blank=True, help_text='Upload the Privacy Policy as a PDF or Word document.', null=True, upload_to='legal_docs/'),
        ),
        migrations.AddField(
            model_name='footersection',
            name='terms_conditions_file',
            field=models.FileField(blank=True, help_text='Upload the Terms & Conditions as a PDF or Word document.', null=True, upload_to='legal_docs/'),
        ),
    ]
