# Generated by Django 5.2.8 on 2026-08-28 07:46

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0014_footersection_privacy_policy_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersection',
            name='privacy_policy_file',
            field=models.FileField(blank=True, help_text='Upload the Privacy Policy as a PDF or Word document.', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='legal_docs/'),
        ),
        migrations.AlterField(
            model_name='footersection',
            name='terms_conditions_file',
            field=models.FileField(blank=True, help_text='Upload the Terms & Conditions as a PDF or Word document.', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='legal_docs/'),
        ),
    ]
